FROM russtedrake/underactuated:8910304
RUN apt update
RUN pip install --upgrade pip
RUN apt install ffmpeg -y
RUN pip install ffmpeg
RUN pip install sympy
RUN pip install numpy
RUN pip install matplotlib
RUN pip install IPython